apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mediaservice
  name: mediaservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediaservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mediaservice
    spec:
      containers:
      - image: penghuiping/media-microservice
        name: media-microservice
        resources:
          requests:
            memory: 256M #内存256M
            cpu: 1000m #1个cpu
          limits:
            memory: 512M
            cpu: 2000m
        livenessProbe: ## 健康检查，重启可以解决
          initialDelaySeconds: 60 #第一次健康检查的时间，需要晚于容器启动时间
          timeoutSeconds: 10
          httpGet:
              port: 8100
              path: /actuator/health
        readinessProbe: ## 启动以后，什么时候容器准备好可以处理外部请求
          timeoutSeconds: 10
          httpGet:
              port: 8100
              path: /actuator/health
status: {}

