########################################################
###common
########################################################
app:
  db:
    ip: ${db_ip}
    port: ${db_port}
    username: ${db_username}
    password: ${db_password}
    name: ${db_name}
  rabbitmq:
    ip: ${rabbitmq_ip}
    port: ${rabbitmq_port}
    username: ${rabbitmq_username}
    password: ${rabbitmq_password}
    virtualHost: ${rabbitmq_virtualHost}
  redis:
    host: ${redis_host}
    port: ${redis_port}
    nodes: ${redis_nodes}
    password: ${redis_password}
    database: ${redis_database}
  filesever:
    host: ${fileServer_host}
    path: ${fileServer_path}
########################################################
### static resources and upload load file
########################################################
base_assets_url: http://${app.filesever.host}/${spring.application.name}/assets/
base_assets_upload_path: ${app.filesever.path}/${spring.application.name}/upload/
base_assets_upload_url: http://${app.filesever.host}/${spring.application.name}/upload/
########################################################
### LOG
########################################################
logging:
  file: logs/userservice.log
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    com.php25: INFO
spring:
  ########################################################
  ###datasource
  ########################################################
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${app.db.ip}:${app.db.port}/${app.db.name}?useUnicode=true&characterEncoding=utf-8
    username: ${app.db.username}
    password: ${app.db.password}
    initSize: 5
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x' FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    publicKey:
    decrypt: false
  ########################################################
  ### Java Persistence Api
  ########################################################
  jpa:
    database: MYSQL
    # Show or not log for each sql query
    show-sql: true
    format-sql: true
    # Hibernate ddl auto (create, create-drop, update)
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        cache:
          use_second_level_cache: false
  ########################################################
  ### JMS Rabbitmq
  ########################################################
#  rabbitmq:
#    host: ${app.rabbitmq.ip}
#    port: ${app.rabbitmq.port}
#    username: ${app.rabbitmq.username}
#    password: ${app.rabbitmq.password}
#    virtualHost: ${app.rabbitmq.virtualHost}
  ########################################################
  ### redis
  ########################################################
  redis:
    host: ${app.redis.host}
    port: ${app.redis.port}
    database: ${app.redis.database}
    ssl: false
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1s
        min-idle: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1s
        min-idle: 0
    timeout: 5s
  #    cluster:
  #      max-redirects: 3
  #      nodes: 10.186.123.159:7380,10.186.123.159:7381,10.186.123.188:7380
  #    sentinel:
  #      master: master
  #      nodes: 10.182.175.63:26380,10.182.175.64:26380
  #    password: ${app.redis.password}
  ########################################################
  ### fileupload
  ########################################################
#  servlet:
#    multipart:
#      max-file-size: 10Mb
#      max-request-size: 1000Mb








