###############################################
## common配置
###############################################
spring:
  profiles:
    active: development
  application:
    name: springbootlearn-userservice
  data:
    redis:
      repositories:
        enabled: false
    elasticsearch:
      repositories:
        enabled: false
server:
  port: 9090
  type: provider
###############################################
## dubbo配置
###############################################
dubbo:
  scan:
    basePackages: com.php25.usermicroservice.server.rpc
  ## ApplicationConfig Bean
  application:
    id: dubbo-provider-userservice
    name: dubbo-provider-userservice
    qos-port: 22222
    qos-enable: true
    qosAcceptForeignIp: false
  ## ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
    serialization: hessian2
  ## RegistryConfig Bean
  registry:
    id: my-registry
    address: zookeeper://localhost:2181
    client: curator
###############################################
## apollo配置
###############################################
app:
  id: java_spring_boot_learn_api
apollo:
  bootstrap:
    enabled: true
  cacheDir: /tmp/data/apollo-cache
  meta: http://localhost:8080

