########################################################
###common
########################################################
app:
  rabbitmq:
    ip: ${rabbitmq_ip}
    port: ${rabbitmq_port}
    username: ${rabbitmq_username}
    password: ${rabbitmq_password}
    virtualHost: ${rabbitmq_virtualHost}
  filesever:
    host: ${fileServer_host}
    path: ${fileServer_path}
  zipkin:
    host: ${zipkin_host}
    port: ${zipkin_port}
  eureka:
    host: ${eureka_ip}
    port: ${eureka_port}
  logstash:
    host: ${log_stash_host}
    port: ${log_stash_port}
spring:
  ########################################################
  ### spring cloud stream
  ########################################################
  rabbitmq:
    addresses: ${app.rabbitmq.ip}
    port: ${app.rabbitmq.port}
    username: ${app.rabbitmq.username}
    password: ${app.rabbitmq.password}
    virtual-host: ${app.rabbitmq.virtualHost}
  cloud:
    stream:
      bindings:
        input:
          group: auditlogservice
          destination: data-exchange
          contentType: application/json
          consumer:
            acknowledgeMode: AUTO
            auto-bind-dlq: true
            republish-to-dlq: true
            max-attempts: 3
#            partitioned: false
        output:
          destination: data-exchange
          contentType: application/json
#          producer:
#            partitioned: false
#            partitionKeyExpression: headers['partitionKey']
#            partitionCount: 1
#      instance-count: 1
#      instance-index: 0
  ########################################################
  ### 调用链监控
  ########################################################
  zipkin:
    base-url: http://${app.zipkin.host}:${app.zipkin.port}
    service.name: springcloudlearn-workflowservice
    sender.type: web
  sleuth:
    sampler:
      probability: 1.0
      rate: 50
    traceId128: true
    opentracing:
      enabled: true
    web:
      client:
        enabled: true
    enabled: true
  ########################################################
  ### mongodb
  ########################################################
  data:
    mongodb:
      host: ${mongodb_host}
      username: ${mongodb_username}
      password: ${mongodb_password}
      port: ${mongodb_port}
      database: ${mongodb_database}
######################################################
### metrics监控
########################################################
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8104
########################################################
### logstash 集中日志
########################################################
logstash:
  ip: ${app.logstash.host}
  port: ${app.logstash.port}
########################################################
### LOG
########################################################
logging:
  file: logs/auditlogservice.log
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.jdbc: INFO
    org.springframework.security.web: debug
    org.hibernate: INFO
    com.php25: INFO
###############################################
## apollo配置中心
###############################################
apollo:
  bootstrap:
    enabled: true
    eagerLoad.enabled: true
    namespaces: application
  cacheDir: /data/apollo-cache
  meta: http://localhost:8080
###############################################
## eureka注册中心配置
##############################################
eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka.host}:${app.eureka.port}/eureka/
    enabled: true
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 5
########################################################
### static resources and upload load file
########################################################
base_assets_url: http://${app.filesever.host}/${spring.application.name}/assets/
base_assets_upload_path: ${app.filesever.path}/${spring.application.name}/upload/
base_assets_upload_url: http://${app.filesever.host}/${spring.application.name}/upload/
########################################################
### jwt rsa
########################################################
jwt:
  publicKey: ${jwt_public_key}
  privateKey: ${jwt_private_key}