########################################################
###common
########################################################
app:
  redis:
    host: ${redis_host}
    port: ${redis_port}
    nodes: ${redis_nodes}
    password: ${redis_password}
    database: ${redis_database}
########################################################
### LOG
########################################################
logging:
  file: logs/gateway.log
  level:
    root: INFO
    com.php25: INFO
    org.springframework.security: INFO
    org.springframework.cloud.sleuth: debug
  pattern:
    level: '[%X{X-B3-TraceId}/%X{X-B3-SpanId}] %-5p [%t] %C{2} - %m%n'
spring:
  ########################################################
  ### redis
  ########################################################
  redis:
    host: ${app.redis.host}
    port: ${app.redis.port}
    database: ${app.redis.database}
    ssl: false
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1s
        min-idle: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1s
        min-idle: 0
    timeout: 5s
  #    cluster:
  #      max-redirects: 3
  #      nodes: 10.186.123.159:7380,10.186.123.159:7381,10.186.123.188:7380
  #    sentinel:
  #      master: master
  #      nodes: 10.182.175.63:26380,10.182.175.64:26380
  #    password: ${app.redis.password}
  data:
    redis:
      repositories:
        enabled: false
    elasticsearch:
      repositories:
        enabled: false
  cloud:
    gateway:
      routes:
      - id: authserver
        uri: lb://SPRINGBOOTLEARN-AUTHSERVER
        predicates:
        - Path=/oauth/**
        filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback
        - RewritePath=/oauth/(?<segment>.*), /oauth/$\{segment}
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 1 #每秒允许处理多少请求
            redis-rate-limiter.burstCapacity: 2 #每个用户每秒允许处理多少请求
      - id: gateway-getMsgCode
        uri: forward:///api/common/getMsgCode.do
        predicates:
        - Path=/api/common/getMsgCode.do
        filters:
        - RewritePath=/openapi/(?<segment>.*), /api/$\{segment}
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 1  #每秒允许处理多少请求
            redis-rate-limiter.burstCapacity: 1  #每个用户每秒允许处理多少请求
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback

hystrix:
  command:
    fallbackcmd:
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 20
        sleepWindowInMilliseconds: 5000
        errorThresholdPercentage: 50
        forceOpen: false
        forceClosed: false
      fallback:
        enabled: true
        isolation:
          semaphore:
            maxConcurrentRequests: 10
      execution:
        isolation:
          strategy: SEMAPHORE
          semaphore:
            maxConcurrentRequests: 10
          thread:
            timeoutInMilliseconds: 1000
            interruptOnTimeout: true
            interruptOnCancel: false
        timeout:
          enabled: true
########################################################
### metrics
########################################################
management:
  endpoints:
    web:
      exposure:
        include: "*"




