apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
## 定义配置从哪里继承
resources:
  - ../base
## 定义需要修改的配置
patchesStrategicMerge:
  - patch-config-map.yaml

configMapGenerator:
  - name: mediaservice-config-map
    files:
      - application.yml
      - application-dev-postgres.yml
