apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mediaservice
  name: mediaservice
spec:
  selector:
    matchLabels:
      app: mediaservice
  template:
    spec:
      volumes:
        - name: mediaservice-config
          configMap:
            name: mediaservice-config-map
      containers:
        - name:  media-microservice
          args:
            - --spring.config.location=/etc/config/application.yml,/etc/config/application-dev-postgres.yml
          volumeMounts:
            - mountPath: /etc/config
              name: mediaservice-config
