########################################################
###common
########################################################
app:
  db:
    ip: ${db_ip}
    port: ${db_port}
    username: ${db_username}
    password: ${db_password}
    name: ${db_workflowservice_name}
  rabbitmq:
    ip: ${rabbitmq_ip}
    port: ${rabbitmq_port}
    username: ${rabbitmq_username}
    password: ${rabbitmq_password}
    virtualHost: ${rabbitmq_virtualHost}
  redis:
    host: ${redis_host}
    port: ${redis_port}
    nodes: ${redis_nodes}
    password: ${redis_password}
    database: ${redis_database}
  filesever:
    host: ${fileServer_host}
    path: ${fileServer_path}
  zipkin:
    host: ${zipkin_host}
    port: ${zipkin_port}
  eureka:
    host: ${eureka_ip}
    port: ${eureka_port}
  logstash:
    host: ${log_stash_host}
    port: ${log_stash_port}
spring:
  ########################################################
  ###datasource
  ########################################################
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${app.db.ip}:${app.db.port}/${db_name}?currentSchema=${app.db.name}
    username: ${app.db.username}
    password: ${app.db.password}
#    initSize: 1
#    minIdle: 1
#    maxActive: 500
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select version();
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxPoolPreparedStatementPerConnectionSize: 20
#    publicKey:
#    decrypt: false
#  ########################################################
#  ### spring cloud stream
#  ########################################################
#  rabbitmq:
#    addresses: ${app.rabbitmq.ip}
#    port: ${app.rabbitmq.port}
#    username: ${app.rabbitmq.username}
#    password: ${app.rabbitmq.password}
#    virtual-host: ${app.rabbitmq.virtualHost}
#  cloud:
#    stream:
#      bindings:
#        input:
#          group: one
#          destination: data-exchange
#          contentType: application/json
#          consumer:
#            acknowledgeMode: AUTO
#            auto-bind-dlq: true
#            republish-to-dlq: true
#            max-attempts: 3
#        output:
#          destination: data-exchange
#          contentType: application/json
#      instance-count: 3
#  ########################################################
#  ### redis
#  ########################################################
#  redis:
#    host: ${app.redis.host}
#    port: ${app.redis.port}
#    database: ${app.redis.database}
#    ssl: false
#    jedis:
#      pool:
#        max-active: 8
#        max-idle: 8
#        max-wait: -1s
#        min-idle: 0
#    lettuce:
#      pool:
#        max-active: 8
#        max-idle: 8
#        max-wait: -1s
#        min-idle: 0
#    timeout: 5s
#  #    cluster:
#  #      max-redirects: 3
#  #      nodes: 10.186.123.159:7380,10.186.123.159:7381,10.186.123.188:7380
#  #    sentinel:
#  #      master: master
#  #      nodes: 10.182.175.63:26380,10.182.175.64:26380
#  #    password: ${app.redis.password}
  ########################################################
  ### 调用链监控
  ########################################################
  zipkin:
    base-url: http://${app.zipkin.host}:${app.zipkin.port}
    service.name: springcloudlearn-workflowservice
    sender.type: web
  sleuth:
    sampler:
      probability: 1.0
      rate: 50
    traceId128: true
    opentracing:
      enabled: true
    web:
      client:
        enabled: true
    enabled: true
########################################################
### metrics监控
########################################################
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8103
########################################################
### logstash 集中日志
########################################################
logstash:
  ip: ${app.logstash.host}
  port: ${app.logstash.port}
########################################################
### LOG
########################################################
logging:
  file: logs/workflowservice.log
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.jdbc: INFO
    org.springframework.security.web: debug
    org.hibernate: INFO
    com.php25: INFO
###############################################
## apollo配置中心
###############################################
apollo:
  bootstrap:
    enabled: true
    eagerLoad.enabled: true
    namespaces: application
  cacheDir: /data/apollo-cache
  meta: http://localhost:8080
###############################################
## eureka注册中心配置
##############################################
eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka.host}:${app.eureka.port}/eureka/
    enabled: true
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 5
########################################################
### static resources and upload load file
########################################################
base_assets_url: http://${app.filesever.host}/${spring.application.name}/assets/
base_assets_upload_path: ${app.filesever.path}/${spring.application.name}/upload/
base_assets_upload_url: http://${app.filesever.host}/${spring.application.name}/upload/
########################################################
### jwt rsa
########################################################
jwt:
  publicKey: ${jwt_public_key}
  privateKey: ${jwt_private_key}