###############################################
## common配置
###############################################
spring:
  profiles:
    active: development
  application:
    name: springbootlearn-admin
server:
  port: 8082
  type: provider
###############################################
## dubbo配置
###############################################
## ApplicationConfig Bean
dubbo:
  application:
    id: dubbo-consumer-admin
    name: dubbo-consumer-admin
    qos-port: 22220
    qos-enable: true
    qosAcceptForeignIp: false
  ## RegistryConfig Bean
  registry:
    id: my-registry
    address: zookeeper://localhost:2181
    client: curator
###############################################
## apollo配置
###############################################
app:
  id: java_spring_boot_learn_api
apollo:
  bootstrap:
    enabled: true
  cacheDir: /data/apollo-cache
  meta: http://localhost:8080